//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPersonnelMedical.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionPersonnelMedical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAjouter {
            get {
                return ResourceManager.GetString("ButtonAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string ButtonModifier {
            get {
                return ResourceManager.GetString("ButtonModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonRechercher {
            get {
                return ResourceManager.GetString("ButtonRechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ButtonReinitialiser {
            get {
                return ResourceManager.GetString("ButtonReinitialiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonSupprimer {
            get {
                return ResourceManager.GetString("ButtonSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation deleted successfully..
        /// </summary>
        public static string ConsultationDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ConsultationDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a Consultation.
        /// </summary>
        public static string ConsultationHeader {
            get {
                return ResourceManager.GetString("ConsultationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation modified successfully..
        /// </summary>
        public static string ConsultationModifiedSuccessfully {
            get {
                return ResourceManager.GetString("ConsultationModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department deleted successfully..
        /// </summary>
        public static string DepartmentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department modified successfully..
        /// </summary>
        public static string DepartmentModifiedSuccessfully {
            get {
                return ResourceManager.GetString("DepartmentModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of departments reset..
        /// </summary>
        public static string DepartmentsListReset {
            get {
                return ResourceManager.GetString("DepartmentsListReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Disponible {
            get {
                return ResourceManager.GetString("Disponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot delete the department as it still contains doctors or nurses..
        /// </summary>
        public static string ErrorDepartmentContainsPersonnel {
            get {
                return ResourceManager.GetString("ErrorDepartmentContainsPersonnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No department selected for modification..
        /// </summary>
        public static string ErrorNoDepartmentSelectedForEdit {
            get {
                return ResourceManager.GetString("ErrorNoDepartmentSelectedForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Please select a consultation to delete..
        /// </summary>
        public static string ErrorSelectConsultationToDelete {
            get {
                return ResourceManager.GetString("ErrorSelectConsultationToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FiltrageHeader {
            get {
                return ResourceManager.GetString("FiltrageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string GestionHeader {
            get {
                return ResourceManager.GetString("GestionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Indisponible {
            get {
                return ResourceManager.GetString("Indisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of nurses reset..
        /// </summary>
        public static string InfirmiersListReset {
            get {
                return ResourceManager.GetString("InfirmiersListReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string LabelDepartement {
            get {
                return ResourceManager.GetString("LabelDepartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability:.
        /// </summary>
        public static string LabelDisponibilite {
            get {
                return ResourceManager.GetString("LabelDisponibilite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string LabelHeure {
            get {
                return ResourceManager.GetString("LabelHeure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurses.
        /// </summary>
        public static string LabelInfirmiers {
            get {
                return ResourceManager.GetString("LabelInfirmiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor:.
        /// </summary>
        public static string LabelMedecin {
            get {
                return ResourceManager.GetString("LabelMedecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string LabelMedecins {
            get {
                return ResourceManager.GetString("LabelMedecins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LabelNom {
            get {
                return ResourceManager.GetString("LabelNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Name:.
        /// </summary>
        public static string LabelParNom {
            get {
                return ResourceManager.GetString("LabelParNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of nurses:.
        /// </summary>
        public static string LabelParNumInf {
            get {
                return ResourceManager.GetString("LabelParNumInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Number of Nurses:.
        /// </summary>
        public static string LabelParNumInfirmiers {
            get {
                return ResourceManager.GetString("LabelParNumInfirmiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of doctors:.
        /// </summary>
        public static string LabelParNumMed {
            get {
                return ResourceManager.GetString("LabelParNumMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Number of Doctors:.
        /// </summary>
        public static string LabelParNumMedecins {
            get {
                return ResourceManager.GetString("LabelParNumMedecins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        public static string LabelPatient {
            get {
                return ResourceManager.GetString("LabelPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string LabelPrenom {
            get {
                return ResourceManager.GetString("LabelPrenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty:.
        /// </summary>
        public static string LabelSpecialite {
            get {
                return ResourceManager.GetString("LabelSpecialite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Personnel Management.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of doctors reset..
        /// </summary>
        public static string MedecinsListReset {
            get {
                return ResourceManager.GetString("MedecinsListReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification saved..
        /// </summary>
        public static string ModificationSaved {
            get {
                return ResourceManager.GetString("ModificationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel deleted successfully..
        /// </summary>
        public static string PersonnelDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PersonnelDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a Consultation.
        /// </summary>
        public static string PlanifierConsultation {
            get {
                return ResourceManager.GetString("PlanifierConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a department..
        /// </summary>
        public static string SelectDepartmentPrompt {
            get {
                return ResourceManager.GetString("SelectDepartmentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a personnel..
        /// </summary>
        public static string SelectPersonnelPrompt {
            get {
                return ResourceManager.GetString("SelectPersonnelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully..
        /// </summary>
        public static string StatusAddedSuccessfully {
            get {
                return ResourceManager.GetString("StatusAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields..
        /// </summary>
        public static string StatusFillAllFields {
            get {
                return ResourceManager.GetString("StatusFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter applied..
        /// </summary>
        public static string StatusFilteredResults {
            get {
                return ResourceManager.GetString("StatusFilteredResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to filter..
        /// </summary>
        public static string StatusNoDataToFilter {
            get {
                return ResourceManager.GetString("StatusNoDataToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation.
        /// </summary>
        public static string TabConsultation {
            get {
                return ResourceManager.GetString("TabConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string TabDepartements {
            get {
                return ResourceManager.GetString("TabDepartements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurses.
        /// </summary>
        public static string TabInfirmiers {
            get {
                return ResourceManager.GetString("TabInfirmiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string TabMedecins {
            get {
                return ResourceManager.GetString("TabMedecins", resourceCulture);
            }
        }
    }
}
